### ISSUE TITLE
I have an issue with ??

### ISSUE THREAD

**Issue by plattnervision** [mcnightschool/blog#14]
@keithbaxter

**Comment by alexlehner** [comment]
Everyone has an issue with @keithbaxter

**Comment by twoesplease** [comment]
Hey Keith isn't all bad

**Comment by alexlehner** [comment]
He has nice hair

**Comment by plattnervision** [comment]
@KyFaSt after some introspection i've discovered the real issue i had was with myself. Sorry @keithbaxter
