### ISSUE TITLE
more freddie butts please

### ISSUE THREAD

**Issue by keithbaxter** [mcnightschool/blog#16]
there's not enough

**Comment by pwnela** [comment]
🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑🍑

**Comment by keithbaxter** [comment]
@pwnela tyvm

**Comment by truelaunch** [comment]
@pwnela - you need one more!

**Comment by pwnela** [comment]
@truelaunch I did it!
