### ISSUE TITLE
I want an office puppy

### ISSUE THREAD

**Issue by Katie28** [mcnightschool/blog#7]
What if we all shared a dog?

**Comment by twoesplease** [comment]
multiple dogs pls

**Comment by KyFaSt** [comment]
great idea, let's definitely do it. What do you think @alexlehner?

**Comment by alexlehner** [comment]
💯 

omg yes

**Comment by alexlehner** [comment]
@Katie28 What kind of dog

**Comment by brentonstrine** [comment]
No. Let's make it an office kitty.

**Comment by Katie28** [comment]
@alexlehner Good question. Let's go classic Golden Retriever.
